feat: label + test
evilfactorylabs/melange-radix-primitives pull request #2
Opened 2024-01-28 07:23 UTC by kevanantha

2024-01-28 11:30 UTC, r17x approved these changes

2024-01-28 11:32 UTC, r17x requested changes
* In npx you could skip request changes when not work with command pnpm

2024-01-28 11:32 UTC, r17x commented on dune
> +  (run npx jest)))
@kevanantha I think can run without `npx` or changes with `pnpm`.

2024-01-28 11:32 UTC, r17x commented on examples/examples.re
> +  <> <LabelRoot> {React.string("This is a label")} </LabelRoot> </>;
Removed **Fragment** in render <LabelRoot/>

2024-01-28 11:32 UTC, r17x commented on src/Label.re
Changes `Label` --> `Radix__Label`

2024-01-28 14:01 UTC, kevanantha commented on src/Label.re
IMO I don't think we need to change that cuz we can call the module `RadixPrimitives.Label`

2024-01-31 14:29 UTC, r17x commented on src/Label.re
@kevanantha I think you must Try in the examples with some filename called `examples/Label.re`.  Based of my knowledge about module system in OCaml/Reason it will be conflicted. CMIIW

2024-01-31 15:25 UTC, kevanantha commented on src/Label.re
here's the examples: https://github.com/evilfactorylabs/melange-radix-primitives/pull/2/files#diff-7e48f0ee77edfcc2de849f12447c5eada9d672d9bd8266126411513f66359ddf

and still work, dune is smart enough to differentiate the module @r17x

2024-01-31 15:31 UTC, kevanantha commented on src/Label.re
if the the name of the library stanza and the filename are the same, you can safely call the module name, you can call `RadixPrimitives.Label` instead of call `RadixPrimitives.RadixPrimitives.Label` 

and I export them in here:
https://github.com/evilfactorylabs/melange-radix-primitives/blob/3f44444b5729bb2ae32cd85a79792d38647d21ad/src/RadixPrimitives.re#L1-L2

the usage is like the link that I sent above

2024-01-31 15:43 UTC, r17x approved these changes
LGBTM 🐫🐴

2024-01-31 17:06 UTC, merged